- name: Install dependencies
  ansible.builtin.package:
    name:
      - fontconfig
      - librust-servo-fontconfig-sys-dev
    state: present
- name: Install alacritty
  become: false
  ansible.builtin.shell: |
    cargo install alacritty
