- name: Restart avahi
  ansible.builtin.systemd:
    name: avahi-daemon
    state: restarted
    enabled: true

- name: Restart smbd
  ansible.builtin.systemd:
    name: smbd
    state: restarted
    enabled: true

- name: Set password
  ansible.builtin.shell: echo {{ samba_password }} | smbpasswd -s -a {{ ansible_user_id }}
