- name: Check if pyenv is installed
  become: false
  ansible.builtin.stat:
    path: ~/.pyenv/bin/pyenv
  register: pyenv
- name: Download pyenv installer
  become: false
  when: pyenv.stat.exists == False
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.run
- name: Install pyenv
  become: false
  when: pyenv.stat.exists == False
  ansible.builtin.shell: bash /tmp/pyenv.run
- name: Setup shell environment for pyenv [.bashrc, .profile]
  become: false
  blockinfile:
    path: "~/.bash_ansible"
    marker: "# {mark} ANSIBLE MANAGED pyenv setup"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="${PYENV_ROOT}/bin:$PATH"
      eval "$(pyenv init -)"
    state: present
    create: true
- name: Setup shell environment for pyenv .zshrc
  become: false
  blockinfile:
    path: ~/.zsh_ansible
    marker: "# {mark} ANSIBLE MANAGED pyenv setup"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
    state: present
    create: true
- name: Install dependencies for pyenv to be able to install python versions
  ansible.builtin.package:
    name:
      - libssl-dev
      - liblzma-dev
      - libsqlite3-dev
      - libffi-dev
      - libbz2-dev

#- name: Install fish if missing
#  ansible.builtin.package:
#    name: fish
#    state: present
#
#- name: Check if pyenv is installed
#  become: false
#  ansible.builtin.stat:
#    path: /usr/bin/fish
#  register: fish
#
#- name: Check if PYENV_ROOT is already set
#  ansible.builtin.shell:
#    executable: /usr/bin/fish
#    cmd: set -q PYENV_ROOT
#  register: pyenv_root
#
#- name: Setup fish for pyenv
#  become: false
#  when: (fish.stat.exists == True) and (pyenv is failed)
#  ansible.builtin.shell:
#    executable: /usr/bin/fish
#    cmd: |
#      set -Ux PYENV_ROOT $HOME/.pyenv
#      fish_add_path $PYENV_ROOT/bin
#
#- name: Setup shell environment for pyenv config.fish
#  become: false
#  when: fish.stat.exists == True
#  lineinfile:
#    path: ~/.config/fish/config.fish
#    line: pyenv init - | source
#    state: present
#    create: false
