- name: Get Node Pub Key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/trusted.gpg.d/nodesource-repo.asc

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_20.x nodistro main"
    state: present
    update_cache: yes

- name: Install Nodejs
  ansible.builtin.apt:
    name: nodejs
    install_recommends: false
    state: present
