- name: Install git
  ansible.builtin.package:
    name:
      - git
      - git-lfs
      - git-doc
    state: present

- name: Install git-delta
  become: false
  ansible.builtin.shell: ~/.cargo/bin/cargo install git-delta
