- name: Setup Developmen Environment on Ubuntu
  hosts: dev
  become: true
  vars_files:
    - vault/vars.yaml
    - vault/vault.yaml
  tasks:
    - name: test vault
      debug:
        msg: "{{ samba.password }}"

#    - name: Show Facts
#      ansible.builtin.debug:
#        var: ansible_facts
