
[window]
opacity = 0.97
blur = true

[font]
size = 12.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Regular Italic"

[general]
import = ["/home/dstadelmann/.config/alacritty/themes/one_dark.toml"]

